@extends('layouts.mainlayout')

@section('title', 'Dashboard')

@section('content')
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, nobis odio! Tenetur distinctio illum, sed tempora deleniti itaque nostrum. Quia atque repellendus eligendi porro necessitatibus ratione voluptatibus rerum? Neque possimus perspiciatis deleniti nam voluptatem a, aspernatur incidunt quisquam voluptates in sunt velit autem culpa nostrum officiis, maiores assumenda! Dolor, esse dicta, suscipit ducimus voluptate fugiat neque vitae cumque repellat quasi enim nesciunt iusto. Vero iure a dolorem molestias tempore ab iusto, fuga unde eligendi totam sapiente quaerat officia esse quas quam, voluptatem dolorum ullam! Animi qui aliquid porro repellendus explicabo assumenda tempore magni, eveniet fugiat natus expedita modi nam amet quasi quis facere delectus rerum magnam consectetur cum, iusto libero quam corrupti. Possimus dolores cupiditate dolore quam deserunt enim repudiandae illum debitis magni. Itaque quaerat nesciunt nostrum vel. Hic et odit modi expedita adipisci? Ullam earum, obcaecati quas accusamus sunt modi consequatur voluptate laudantium alias ratione rerum, atque nesciunt. Eos quasi qui omnis pariatur eveniet officia impedit laboriosam libero quisquam, facilis dolore expedita culpa, totam alias itaque quo! Voluptatibus dignissimos quod itaque praesentium ut consequatur reprehenderit velit ipsam illo, id veniam, dicta suscipit maxime modi. Eius cumque sunt dolorem molestias assumenda similique veniam consectetur dolore, possimus alias explicabo amet hic dolores ea quos sit nihil incidunt! Voluptatem, vitae autem repellat doloribus voluptates quaerat, omnis eligendi nisi reiciendis porro deserunt fugit iusto harum labore qui molestias totam quis excepturi dolorum quam. Dolore reiciendis magnam qui iste ex pariatur praesentium unde temporibus voluptates? Assumenda aliquam optio accusamus laboriosam quaerat natus non dicta culpa deleniti quod! Soluta excepturi culpa, quaerat aspernatur architecto mollitia modi quas nihil laborum aperiam. Eos possimus quod corrupti aliquam fuga obcaecati sapiente at optio vel similique alias doloremque eum necessitatibus vitae omnis laudantium repellat, perferendis iste quas minus a. Expedita facere blanditiis placeat omnis reiciendis impedit rerum maxime! Dolor?
    </p>
@endsection
    